# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:
    inputs:
      disable-cache:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # ratchet:dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # ratchet:Swatinem/rust-cache@v2
        if: ${{ inputs.disable-cache != true }}

      - name: Install cargo-auditable
        uses: taiki-e/install-action@c070f87102a1c75b3183910f391c1cb887fe13c8 # ratchet:taiki-e/install-action@v2
        with:
          tool: cargo-auditable

      - name: Build
        run: cargo auditable build --release --locked --target ${{ matrix.target }}
        env:
          CARGO_PROFILE_RELEASE_LTO: "fat"
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"

      - name: Rename artifact
        run: cp ./target/${{ matrix.target }}/release/am ./am-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@v7
        with:
          name: am-${{ matrix.target }}
          path: ./am-${{ matrix.target }}
